# Generated by Django 3.0.8 on 2020-07-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
